name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
    
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup and run checks
        run: |
          cd cicd-assignments/task-1  # adjust if capitalized
          pip install -r requirements.txt
          flake8 .
          pytest
          docker build -t test-image -f Dockerfile .